const referenciaMunicipios = [
    "Andaraí",
    "Barra da Estiva",
    "Barro Alto",
    "Boninal",
    "Ibicoara",
    "Iramaia",
    "Iraquara",
    "Itaetê",
    "Lençóis",
    "Mucugê",
    "Mulungu do Morro",
    "Nova Redenção",
    "Palmeiras",
    "Piatã",
    "Seabra",
    "Souto Soares",
    "Ibitiara",
    "Conceição do Coité",
    "Ipirá",
    "Itatim",
    "Pé de Serra",
    "Rafael Jambeiro",
    "Riachão do Jacuípe",
    "Santa Terezinha",
    "Santo Estêvão",
    "Serra Preta",
    "Serrinha",
    "Tanquinho",
    "Barrocas",
    "Candeal",
    "Ichu",
    "Ipecaetá",
    "Santa Bárbara",
    "Castro Alves",
    "Baixa Grande",
    "Boa Vista do Tupim",
    "Bonito",
    "Capela do Alto Alegre",
    "Gavião",
    "Iaçu",
    "Ibiquera",
    "Itaberaba",
    "Lajedinho",
    "Macajuba",
    "Mairi",
    "Maracás",
    "Marcionílio Souza",
    "Miguel Calmon",
    "Milagres",
    "Morro do Chapéu",
    "Mundo Novo",
    "Nova Fátima",
    "Pintadas",
    "Piritiba",
    "Planaltino",
    "Quixabeira",
    "Retirolândia",
    "Ruy Barbosa",
    "Santaluz",
    "São Domingos",
    "São José do Jacuípe",
    "Serrolândia",
    "Tapiramutá",
    "Utinga",
    "Várzea da Roça",
    "Várzea do Poço",
    "Wagner",
    "Nova Itarana",
    "Valente",
    "Cachoeira",
    "Maragogipe",
    "Saubara",
    "Anguera",
    "Antônio Cardoso",
    "Cabaceiras do Paraguaçu",
    "Conceição da Feira",
    "Cruz das Almas",
    "Feira de Santana",
    "Governador Mangabeira",
    "Muritiba",
    "São Félix",
    "São Gonçalo dos Campos",
    "Sapeaçu",
    "Novo Horizonte",
    "Capim Grosso",
    "Jaguaripe",
    "Nazaré",
    "Salinas da Margarida",
    "São Felipe"
];

module.exports = referenciaMunicipios;